### ISSUE TITLE
Newline did not parse

### ISSUE THREAD

**Issue by devmarkpro** [Ncrypt-Site/ncrypt-api#1]
New lines are removed when the receiver decrypts the note.

for example, I encrypted the text below:
```
Username: xxx
Password: yyy
```
And what the receiver saw was:
```
Username: xxx Password: yyy
```

OS: macOS Catalina 10.15.5
Browser: Google Chrome Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by miladd3** [comment]
@ph4r5h4d Its a CSS issue and I will fix it in the next update

**Comment by miladd3** [comment]
@ph4r5h4d It's fixed now in client master branch

**Comment by ph4r5h4d** [comment]
will be released with the next version.
