### ISSUE TITLE
Notes can be decrypted with two passwords

### ISSUE THREAD

**Issue by mhmazrooei** [Ncrypt-Site/ncrypt-api#2]
The app gives you a password with an equal sign (=) at the end.

You can decrypt a note with or without (=) 

Example:
`https://ncrypt.site/note/eaf16f92-19c7-4982-8db4-4812d1293f96`

Password:
`Ung3UlVYdER4eG82d2plV2E2eERuVnR1Rkk4R3hDbDk=`

 The note can be opened with or without the equal sign

**Comment by ph4r5h4d** [comment]
Hi,
Passwords are base64 encoded strings, the `=` or `==` at the end of the passwords are paddings from the base64 function, with or without them you get the same decoded response, so it's okay.
